### ISSUE TITLE
Couldn't find index page for 'pyqt' (maybe misspelled?)

### ISSUE THREAD

**Issue by lc30705** [nakulrampal/betsi-gui#2]
Hi I have followed the option 2: using the source code to install the package. However, i have received this error:

Installed c:\users\lc3\anaconda3\envs\betsi new\lib\site-packages\betsi-1.0.0-py3.7.egg
Processing dependencies for betsi==1.0.0
Searching for pyqt
Reading https://pypi.org/simple/pyqt/
Couldn't find index page for 'pyqt' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for pyqt
error: Could not find suitable distribution for Requirement.parse('pyqt')

May I ask if you know how to solve this issue?

Many thanks in advance.

**Comment by nakulrampal** [comment]
Thanks for reaching out, @lc30705! 

What version of Python are you using?

**Comment by lc30705** [comment]
Hi Nakul, the version i am using is 3.7.10

**Comment by nakulrampal** [comment]
Could you please try compiling the code running python version 3.7.3 in your conda environment? 

To do this, you can run the following commands in the terminal/command prompt: 
```
conda activate my_env (insert name of your env in place of "my_env")
conda install python=3.7.3
```
Some other commands which may be helpful:

To rebuild an environment: 
```
conda create --name my_env python=3.7.3
```
To check the version of python installed:
```
python --version
```
Once you've installed BETSI, you can check the list of packages installed in the environment using:
```
conda list -n my_env
```

**Comment by lc30705** [comment]
Thanks Nakul! I am installing Python 3.7.3 now. I will let you know if there is further issue.

**Comment by lc30705** [comment]
Hi Nakul, I am still having the same error message about "pyqt", although have installed python 3.7.3. :(

**Comment by nakulrampal** [comment]
That's interesting.. let me try re-compiling it too

**Comment by lc30705** [comment]
Installed c:\users\lc3\anaconda3\envs\betsi new\lib\site-packages\betsi-1.0.0-py3.7.egg
Processing dependencies for betsi==1.0.0
Searching for pyqt
Reading https://pypi.org/simple/pyqt/
Couldn't find index page for 'pyqt' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for pyqt
error: Could not find suitable distribution for Requirement.parse('pyqt')

**Comment by nakulrampal** [comment]
I think it should work now, please see 27699df5d0d2528652d4aed9dd375cced80b00c8 for the changes made.

First you will have to run the command: 
```
python setup.py install
```
Followed by:
```
pip install .
```

**Comment by nakulrampal** [comment]
I think it should work now, please see 27699df5d0d2528652d4aed9dd375cced80b00c8 and f559bafea1cffe5fb08a8db75ccf63fa21ebc595 for the changes made.

First, you will have to run the command: 
```
python setup.py install
```
Followed by:
```
pip install .
```
