### ISSUE TITLE
ValueError for certain CSV files

### ISSUE THREAD

**Issue by gianmarco-terrones** [nakulrampal/betsi-gui#8]
BETSI errors out with a ValueError when I try to analyze a CSV file:

**Contents of CSV file:**
Relative Pressure   (P/Po) | Quantity Adsorbed (cm3/g STP)
1.00E-09 | 18.0356403
5.00E-09 | 19.0232405
1.00E-08 | 19.6234265
5.00E-08 | 24.0575953
1.00E-07 | 28.7036567
5.00E-07 | 45.1667205
1.00E-06 | 50.063465
5.00E-06 | 62.7085024
1.00E-05 | 69.325213
5.00E-05 | 86.7219313
0.0001 | 103.59786
0.0002 | 138.428492
0.0003 | 173.867323
0.0004 | 198.63714
0.0005 | 215.262565
0.0006 | 229.451773
0.0007 | 238.758325
0.0008 | 250.334132
0.0009 | 259.600475
0.001 | 267.477112
0.0015 | 298.379209
0.002 | 320.859558
0.0025 | 338.47459
0.003 | 354.412843
0.0035 | 361.046793
0.004 | 366.594164
0.0045 | 373.47385
0.005 | 377.015246
0.0055 | 381.506992
0.006 | 382.869757
0.0065 | 390.221516
0.007 | 395.531369
0.0075 | 397.573275
0.008 | 400.433289
0.0085 | 402.203987
0.009 | 399.343974
0.0095 | 407.51384
0.01 | 405.061759
0.015 | 421.128043
0.02 | 433.383963
0.025 | 437.467776
0.03 | 456.257348
0.035 | 470.826383
0.04 | 476.136236
0.045 | 486.755942
0.05 | 490.431822
0.055 | 491.794587
0.06 | 496.423057
0.065 | 497.375648
0.07 | 510.855367
0.075 | 511.53675
0.08 | 514.804697
0.085 | 533.320819
0.09 | 530.189598
0.095 | 524.606295
0.1 | 545.984673
0.2 | 602.487873
0.3 | 624.682117
0.4 | 609.705149
0.5 | 615.830868
0.6 | 616.648975
0.7 | 635.028373
0.8 | 640.474951
0.9 | 642.927032
1 | 629.99197

**Error message:**
```
(betsi) gianmarcoterrones@Gianmarcos-MBP Downloads % python -m betsi
Imported file: MIL-100_Cr.csv
/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/python3.7/site-packages/betsi/lib.py:45: RuntimeWarning: divide by zero encountered in true_divide
  self.linear_y = (pressure / (q_adsorbed * (1. - pressure)))
/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/python3.7/site-packages/numpy-1.19.3-py3.7-macosx-10.9-x86_64.egg/numpy/core/_methods.py:202: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/python3.7/site-packages/betsi/plotting.py:298: MatplotlibDeprecationWarning: Using a string of single character colors as a color sequence is deprecated. Use an explicit list instead.
  ax.scatter(bet_filtered.pressure[min_i:min_j + 1], bet_filtered.rouq_y[min_i:min_j + 1], marker='s', color='red', edgecolors='', label='Linear Range', alpha=0.50)
Traceback (most recent call last):
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/pytho
[MIL-100_Cr.csv](https://github.com/nakulrampal/betsi-gui/files/11470411/MIL-100_Cr.csv)
[MIL-100_Cr.csv](https://github.com/nakulrampal/betsi-gui/files/11470413/MIL-100_Cr.csv)
n3.7/site-packages/betsi/gui.py", line 118, in dropEvent
    self.betsi_widget.run_calculation()
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/python3.7/site-packages/betsi/gui.py", line 344, in run_calculation
    self.plot_bet()
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/python3.7/site-packages/betsi/gui.py", line 299, in plot_bet
    self.target_filepath).stem,  fig=self.current_fig)
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/python3.7/site-packages/betsi/plotting.py", line 199, in create_matrix_plot
    plot_area_error_1(bet_filtered, ax, ax2)
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/python3.7/site-packages/betsi/plotting.py", line 393, in plot_area_error_1
    ax.scatter(x_coords_nonvalid, y_coords_nonvalid, color='red', edgecolors='red', picker=5, alpha =0.5)
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/python3.7/site-packages/matplotlib-3.2.2-py3.7-macosx-10.9-x86_64.egg/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/python3.7/site-packages/matplotlib-3.2.2-py3.7-macosx-10.9-x86_64.egg/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/Users/gianmarcoterrones/opt/anaconda3/envs/betsi/lib/python3.7/site-packages/matplotlib-3.2.2-py3.7-macosx-10.9-x86_64.egg/matplotlib/axes/_axes.py", line 4391, in scatter
    raise ValueError("x and y must be the same size")
ValueError: x and y must be the same size
zsh: abort      python -m betsi
```

**Comment by gianmarco-terrones** [comment]
Running BETSI with the following settings:
![image](https://github.com/nakulrampal/betsi-gui/assets/78051991/ce5be31f-2d61-4e3d-9a5e-7093fcce0b7b)

**Comment by gianmarco-terrones** [comment]
It seems the issue is that `x_coords_nonvalid` and `y_coords_nonvalid` are not the same length.

**Comment by nakulrampal** [comment]
Thanks for bringing this up, @gianmarco-terrones! We now have a new version that you may want to try with your data - the executables can be found in the following repo: [betsi-gui](https://github.com/fairen-group/betsi-gui)

Also, a list of all the new features/bug fixes that we have added can be found here: [features-list](https://github.com/fairen-group/betsi-gui/blob/master/BETSI-v2.0.pdf)

Please feel free to let us know if you have any other questions/comments - we are always happy to help :)
